{% set name = "xcube-eopf" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/EOPF-Sample-Service/xcube-eopf/archive/v{{ version }}.tar.gz
  sha256: 50977449ecd3ba961367fb907fd37639776976ead3f8a16a6e49558a0d384f44

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dask
    - numpy
    - pyproj
    - pystac
    - pystac-client
    - xarray
    - xarray-eopf
    - xcube >=1.11.0
test:
  imports:
    - xcube_eopf
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A xcube datastore implementation that allows for analysis-ready reading of ESA EOPF data products.
  home: https://github.com/EOPF-Sample-Service/xcube-eopf
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: xcube-eopf is a Python package
  dev_url: https://github.com/EOPF-Sample-Service/xcube-eopf

extra:
  recipe-maintainers:
    - konstntokas
    - forman
